name: PR Checklist

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches: [dev, main]

jobs:
  checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Vérification des cases obligatoires du PR template
        uses: mheap/require-checklist-action@v2
        with:
          requireChecklist: true
